version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html/src
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/clean_deployment_directory.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
