version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html
    overwrite: yes
    ignore:
      - .gitignore
      - README.md
      - appspec.yml
      - src
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
